apiVersion: v1
kind: Service
metadata:
  name: tier1-service
spec:
  selector:
    app: tier1-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tier2-service
spec:
  selector:
    app: tier2-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tier3-service
spec:
  selector:
    app: tier3-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080