apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-hub-app-management-spring-apps-service-account-binding
subjects:
  - kind: ServiceAccount
    name: tanzu-hub-app-management-spring-apps-service-account
    namespace: app-management-spring-demo
roleRef:
  kind: ClusterRole
  name: telegraf-k8s-role-aria-telegraf-collector
  apiGroup: rbac.authorization.k8s.io