apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-apps-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-apps-db
  template:
    metadata:
      labels:
        app: demo-apps-db
    spec:
      serviceAccountName: tanzu-hub-app-management-spring-apps-service-account
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: demo-apps-db-container
          image: symphony-docker-local.jfrog.io/tanzu/hub/app/spring/demo-apps-db:3
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: demo-apps-db
spec:
  selector:
    app: demo-apps-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432