apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJzeW1waG9ueS1kb2NrZXItbG9jYWwuamZyb2cuaW8iOiB7CiAgICAgICJhdXRoIjogImJUSmxhREk1TjJ0emNXZDBPbUZaV1hWbGQxSXlKbGxkTGpJNVpWOD0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson