apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  selector:
    app: deployment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: approval-service
spec:
  selector:
    app: approval-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: provision-service
spec:
  selector:
    app: provision-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084